/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DigitalMarketingSoftwareDelhiNcrRouteImport } from './routes/digital-marketing-software-delhi-ncr'
import { Route as GoogleAdsAgencyNoidaRouteImport } from './routes/google-ads-agency-noida'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as SeoServicesNoidaRouteImport } from './routes/seo-services-noida'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ApiLeadsRouteImport } from './routes/api/leads'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio/index'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio/$slug'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesServiceRouteImport } from './routes/services/$service'
import { Route as ServicesAdsRouteImport } from './routes/services/ads'
import { Route as ServicesEventsRouteImport } from './routes/services/events'
import { Route as ServicesSeoRouteImport } from './routes/services/seo'
import { Route as ServicesSocialRouteImport } from './routes/services/social'
import { Route as ServicesSoftwareRouteImport } from './routes/services/software'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalMarketingSoftwareDelhiNcrRoute =
  DigitalMarketingSoftwareDelhiNcrRouteImport.update({
    id: '/digital-marketing-software-delhi-ncr',
    path: '/digital-marketing-software-delhi-ncr',
    getParentRoute: () => rootRouteImport,
  } as any)
const GoogleAdsAgencyNoidaRoute = GoogleAdsAgencyNoidaRouteImport.update({
  id: '/google-ads-agency-noida',
  path: '/google-ads-agency-noida',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoServicesNoidaRoute = SeoServicesNoidaRouteImport.update({
  id: '/seo-services-noida',
  path: '/seo-services-noida',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceRoute = ServicesServiceRouteImport.update({
  id: '/services/$service',
  path: '/services/$service',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAdsRoute = ServicesAdsRouteImport.update({
  id: '/services/ads',
  path: '/services/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesEventsRoute = ServicesEventsRouteImport.update({
  id: '/services/events',
  path: '/services/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSeoRoute = ServicesSeoRouteImport.update({
  id: '/services/seo',
  path: '/services/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSocialRoute = ServicesSocialRouteImport.update({
  id: '/services/social',
  path: '/services/social',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSoftwareRoute = ServicesSoftwareRouteImport.update({
  id: '/services/software',
  path: '/services/software',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/digital-marketing-software-delhi-ncr': typeof DigitalMarketingSoftwareDelhiNcrRoute
  '/google-ads-agency-noida': typeof GoogleAdsAgencyNoidaRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/process': typeof ProcessRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/seo-services-noida': typeof SeoServicesNoidaRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/work': typeof WorkRoute
  '/api/leads': typeof ApiLeadsRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/$service': typeof ServicesServiceRoute
  '/services/ads': typeof ServicesAdsRoute
  '/services/events': typeof ServicesEventsRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/social': typeof ServicesSocialRoute
  '/services/software': typeof ServicesSoftwareRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/digital-marketing-software-delhi-ncr': typeof DigitalMarketingSoftwareDelhiNcrRoute
  '/google-ads-agency-noida': typeof GoogleAdsAgencyNoidaRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/process': typeof ProcessRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/seo-services-noida': typeof SeoServicesNoidaRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/work': typeof WorkRoute
  '/api/leads': typeof ApiLeadsRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/$service': typeof ServicesServiceRoute
  '/services/ads': typeof ServicesAdsRoute
  '/services/events': typeof ServicesEventsRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/social': typeof ServicesSocialRoute
  '/services/software': typeof ServicesSoftwareRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/services': typeof ServicesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/digital-marketing-software-delhi-ncr': typeof DigitalMarketingSoftwareDelhiNcrRoute
  '/google-ads-agency-noida': typeof GoogleAdsAgencyNoidaRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/process': typeof ProcessRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/seo-services-noida': typeof SeoServicesNoidaRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/work': typeof WorkRoute
  '/api/leads': typeof ApiLeadsRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/$service': typeof ServicesServiceRoute
  '/services/ads': typeof ServicesAdsRoute
  '/services/events': typeof ServicesEventsRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/social': typeof ServicesSocialRoute
  '/services/software': typeof ServicesSoftwareRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/digital-marketing-software-delhi-ncr'
    | '/google-ads-agency-noida'
    | '/login'
    | '/privacy-policy'
    | '/process'
    | '/refund-policy'
    | '/seo-services-noida'
    | '/studio'
    | '/terms'
    | '/work'
    | '/api/leads'
    | '/portfolio/$slug'
    | '/services/$service'
    | '/services/ads'
    | '/services/events'
    | '/services/seo'
    | '/services/social'
    | '/services/software'
    | '/portfolio/'
    | '/services/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/digital-marketing-software-delhi-ncr'
    | '/google-ads-agency-noida'
    | '/login'
    | '/privacy-policy'
    | '/process'
    | '/refund-policy'
    | '/seo-services-noida'
    | '/studio'
    | '/terms'
    | '/work'
    | '/api/leads'
    | '/portfolio/$slug'
    | '/services/$service'
    | '/services/ads'
    | '/services/events'
    | '/services/seo'
    | '/services/social'
    | '/services/software'
    | '/portfolio'
    | '/services'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/digital-marketing-software-delhi-ncr'
    | '/google-ads-agency-noida'
    | '/login'
    | '/privacy-policy'
    | '/process'
    | '/refund-policy'
    | '/seo-services-noida'
    | '/studio'
    | '/terms'
    | '/work'
    | '/api/leads'
    | '/portfolio/$slug'
    | '/services/$service'
    | '/services/ads'
    | '/services/events'
    | '/services/seo'
    | '/services/social'
    | '/services/software'
    | '/portfolio/'
    | '/services/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DigitalMarketingSoftwareDelhiNcrRoute: typeof DigitalMarketingSoftwareDelhiNcrRoute
  GoogleAdsAgencyNoidaRoute: typeof GoogleAdsAgencyNoidaRoute
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProcessRoute: typeof ProcessRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  SeoServicesNoidaRoute: typeof SeoServicesNoidaRoute
  StudioRoute: typeof StudioRoute
  TermsRoute: typeof TermsRoute
  WorkRoute: typeof WorkRoute
  ApiLeadsRoute: typeof ApiLeadsRoute
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  ServicesServiceRoute: typeof ServicesServiceRoute
  ServicesAdsRoute: typeof ServicesAdsRoute
  ServicesEventsRoute: typeof ServicesEventsRoute
  ServicesSeoRoute: typeof ServicesSeoRoute
  ServicesSocialRoute: typeof ServicesSocialRoute
  ServicesSoftwareRoute: typeof ServicesSoftwareRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-marketing-software-delhi-ncr': {
      id: '/digital-marketing-software-delhi-ncr'
      path: '/digital-marketing-software-delhi-ncr'
      fullPath: '/digital-marketing-software-delhi-ncr'
      preLoaderRoute: typeof DigitalMarketingSoftwareDelhiNcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-ads-agency-noida': {
      id: '/google-ads-agency-noida'
      path: '/google-ads-agency-noida'
      fullPath: '/google-ads-agency-noida'
      preLoaderRoute: typeof GoogleAdsAgencyNoidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-services-noida': {
      id: '/seo-services-noida'
      path: '/seo-services-noida'
      fullPath: '/seo-services-noida'
      preLoaderRoute: typeof SeoServicesNoidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$service': {
      id: '/services/$service'
      path: '/services/$service'
      fullPath: '/services/$service'
      preLoaderRoute: typeof ServicesServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ads': {
      id: '/services/ads'
      path: '/services/ads'
      fullPath: '/services/ads'
      preLoaderRoute: typeof ServicesAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/events': {
      id: '/services/events'
      path: '/services/events'
      fullPath: '/services/events'
      preLoaderRoute: typeof ServicesEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/seo': {
      id: '/services/seo'
      path: '/services/seo'
      fullPath: '/services/seo'
      preLoaderRoute: typeof ServicesSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/social': {
      id: '/services/social'
      path: '/services/social'
      fullPath: '/services/social'
      preLoaderRoute: typeof ServicesSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/software': {
      id: '/services/software'
      path: '/services/software'
      fullPath: '/services/software'
      preLoaderRoute: typeof ServicesSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DigitalMarketingSoftwareDelhiNcrRoute: DigitalMarketingSoftwareDelhiNcrRoute,
  GoogleAdsAgencyNoidaRoute: GoogleAdsAgencyNoidaRoute,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProcessRoute: ProcessRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  SeoServicesNoidaRoute: SeoServicesNoidaRoute,
  StudioRoute: StudioRoute,
  TermsRoute: TermsRoute,
  WorkRoute: WorkRoute,
  ApiLeadsRoute: ApiLeadsRoute,
  PortfolioSlugRoute: PortfolioSlugRoute,
  ServicesServiceRoute: ServicesServiceRoute,
  ServicesAdsRoute: ServicesAdsRoute,
  ServicesEventsRoute: ServicesEventsRoute,
  ServicesSeoRoute: ServicesSeoRoute,
  ServicesSocialRoute: ServicesSocialRoute,
  ServicesSoftwareRoute: ServicesSoftwareRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
